const data = [
    {
      Code: '1',
      Name: 'Mohammed Saleh',
      MDate: 2020,
      Brand: 'Toyota',
      Model:'Corolla',
      Color:'Grey',
      Image:'/avatar/C1.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '2',
      Name: 'Bassam Mohammed',
      MDate: 2019,
      Brand: 'WAYMO',
      Model:'Magic',
      Color:'White',
      Image:'/avatar/C2.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '3',
      Name: 'Abdu Nasser',
      MDate: 2018,
      Brand: 'Volkswagen',
      Model:'Golf GTI',
      Color:'Black',
      Image:'/avatar/C3.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '4',
      Name: 'Hamza Ossama',
      MDate: 2020,
      Brand: 'Ferrari',
      Model:'LaFerrari',
      Color:'Red',
      Image:'/avatar/C4.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '5',
      Name: 'Yahya Ammar',
      MDate: 2020,
      Brand: 'Suzuki',
      Model:'Maruti Swift',
      Color:'Red',
      Image:'/avatar/C5.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '6',
      Name: 'Arafat Ahmed',
      MDate: 2018,
      Brand: 'Audi',
      Model:'RS7',
      Color:'Black',
      Image:'/avatar/C6.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '7',
      Name: 'Yaser Omar',
      MDate: 1960,
      Brand: 'Ford',
      Model:'Factory',
      Color:'Red',
      Image:'/avatar/C7.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '8',
      Name: 'Abdullah Khaled',
      MDate: 1973,
      Brand: 'Ford',
      Model:'Capri',
      Color:'Yellow',
      Image:'/avatar/C8.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '9',
      Name: 'Kadi Rashed',
      MDate: 2021,
      Brand: 'Professional',
      Model:'X',
      Color:'Green',
      Image:'/avatar/C9.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '10',
      Name: 'Khaled Ali',
      MDate: 2021,
      Brand: 'Tesla',
      Model:'3',
      Color:'White',
      Image:'/avatar/C10.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '11',
      Name: 'Asaad Saad',
      MDate: 2020,
      Brand: 'London No. 1 Lake Park',
      Model:'Infinity',
      Color:'Hardtop',
      Image:'/avatar/C11.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '12',
      Name: 'Abdourahman Momtaz',
      MDate: 2017,
      Brand: 'Domov',
      Model:'Avant2Go',
      Color:'Blue',
      Image:'/avatar/C12.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '13',
      Name: 'Mustafa Kazem',
      MDate: 1957,
      Brand: 'Aston Martin',
      Model:' DB2/4 Mk2 Tickford Coupé',
      Color:'Red',
      Image:'/avatar/C13.jfif',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
  ];
  export default data