const data = [
    {
      Code: '1',
      Name: 'Lavone Parra',
      MDate: 789,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '2',
      Name: 'Rosita Dejohn',
      MDate: 6789,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '3',
      Name: 'Merrill Mayor',
      MDate: 6789,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '4',
      Name: 'Kraig Ayres',
      MDate: 6789,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '5',
      Name: 'Bulah Cunha',
      MDate: 3789,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '6',
      Name: 'Chadwick Aday',
      MDate: 5589,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '7',
      Name: 'Lucy Arehart',
      MDate: 5689,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '8',
      Name: 'Fidelia Harpin',
      MDate: 569,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '9',
      Name: 'Alaina Brim',
      MDate: 687,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '10',
      Name: 'Torie Showman',
      MDate: 6789,
      Brand: 'BMW',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '11',
      Name: 'Rayna Suazo',
      MDate: 6789,
      Brand: 'London No. 1 Lake Park',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '12',
      Name: 'Evangeline Murrin',
      MDate: 6789,
      Brand: 'Sidney No. 1 Lake Park',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
    {
      Code: '13',
      Name: 'Hyacinth Hanson',
      MDate: 6789,
      Brand: 'London No. 2 Lake Park',
      Model:'M5',
      Color:'White',
      Image:'/avatar/002.jpg',
      File:'1',
      Edit:'1',
      Del:'2',
      Car:'2',
      Tool:'3',
    },
  ];
  export default data