import Dashboard from './Dashboard'
import Invoices from './Invoices'
import NewInv from './Invoices/NewInv'
import Contracts from './Contracts'
import NewCon from './Contracts/NewCon'
import Clients from './Clients/'
import NewCls from './Clients/NewCls'
import Services from './Services/'
import NewCar from './Services/NewCar'
import Employees from './Employees/'
import NewEmp from './Employees/NewEmp'
import PurchasesR from './Reports/PurchasesR'
import ContractsR from './Reports/ContractsR'
import ClientsR from './Reports/ClientsR'
import ServicesR from './Reports/ServicesR'
import EmployeesR from './Reports/EmployeesR'
import Account from './Settings/Account'
import SMTP from './Settings/SMTP'
export {Dashboard,Invoices,NewInv,Contracts,NewCon,Clients,
        NewCls,Services,NewCar,Employees,NewEmp,PurchasesR,
        ContractsR,ClientsR,ServicesR,EmployeesR,Account,SMTP}