const data = [
    {
      Code: '1',
      Name: 'Mohammed Saleh',
      Phone: '01101401234',
      Adress: '6th Floor, Khobar Gate Tower King Fahad Road Al khobar KSA',
      Status:'Not Active',
      Image:'/avatar/S1.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '2',
      Name: 'Bassam Mohammed',
      Phone: '01155201234',
      Adress: 'Nakheel , Pr. Turkey Al-AWOL Road,ITCC , RD-01 Building, 4th floor,PO Box 19319, Riyadh  11435',
      Status:'Active',
      Image:'/avatar/S2.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '3',
      Name: 'Abdu Nasser',
      Phone: '01101606234',
      Adress: 'King Fahad Road. Riyadh 11533',
      Status:'Active',
      Image:'/avatar/S3.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '4',
      Name: 'Hamza Ossama',
      Phone: '01661201234',
      Adress: '6th Floor, Khobar Gate Tower King Fahad Road Al khobar KSA',
      Status:'Not Active',
      Image:'/avatar/S4.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '5',
      Name: 'Yahya Ammar',
      Phone: '01101201994',
      Adress: 'Jameel Square Cross Road andalus street and Tahlya Office number 705 Jeddah',
      Status:'Not Active',
      Image:'/avatar/S5.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '6',
      Name: 'Arafat Ahmed',
      Phone: '01101288234',
      Adress: 'Makkah Al-Mukaramah Street P.O. Box 2526',
      Status:'Active',
      Image:'/avatar/S6.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '7',
      Name: 'Yaser Omar',
      Phone: '0110177234',
      Adress: 'Jameel Square Cross Road andalus street and Tahlya Office number 705 Jeddah',
      Status:'Active',
      Image:'/avatar/S7.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '8',
      Name: 'Abdullah Khaled',
      Phone: '01551201234',
      Adress: 'Jameel Square Cross Road andalus street and Tahlya Office number 705 Jeddah',
      Status:'Not Active',
      Image:'/avatar/S8.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '9',
      Name: 'Kadi Rashed',
      Phone: '01122201234',
      Adress: 'Makkah Al-Mukaramah Street P.O. Box 2526',
      Status:'Active',
      Image:'/avatar/S9.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '10',
      Name: 'Khaled Ali',
      Phone: '0110111234',
      Adress: 'Nakheel , Pr. Turkey Al-AWOL Road,ITCC , RD-01 Building, 4th floor,PO Box 19319, Riyadh  11435',
      Status:'Active',
      Image:'/avatar/S10.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '11',
      Name: 'Asaad Saad',
      Phone: '01101691234',
      Adress: 'King Fahad Road. Riyadh 11533',
      Status:'Active',
      Image:'/avatar/S11.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '12',
      Name: 'Abdourahman Momtaz',
      Phone: '01101651234',
      Adress: '6th Floor, Khobar Gate Tower King Fahad Road Al khobar KSA',
      Status:'Active',
      Image:'/avatar/S12.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '13',
      Name: 'Mustafa Kazem',
      Phone: '01101541234',
      Adress: 'King Fahad Road. Riyadh 11533',
      Status:'Not Active',
      Image:'/avatar/S13.jfif',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
  ];
  export default data