const data = [
    {
      Code: '1',
      Name: 'Lavone Parra',
      Phone: 2343456789,
      Country: 'New York No. 1 Lake Park',
      Status:'Not Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '2',
      Name: 'Rosita Dejohn',
      Phone: 13344456789,
      Country: 'New York No. 1 Lake Park',
      Status:'Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '3',
      Name: 'Merrill Mayor',
      Phone: 13323456789,
      Country: 'New York No. 1 Lake Park',
      Status:'Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '4',
      Name: 'Kraig Ayres',
      Phone: 12123456789,
      Country: 'New York No. 1 Lake Park',
      Status:'Not Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '5',
      Name: 'Bulah Cunha',
      Phone: 10123423789,
      Country: 'New York No. 1 Lake Park',
      Status:'Not Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '6',
      Name: 'Chadwick Aday',
      Phone: 10123345589,
      Country: 'New York No. 1 Lake Park',
      Status:'Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '7',
      Name: 'Lucy Arehart',
      Phone: 10123445689,
      Country: 'New York No. 1 Lake Park',
      Status:'Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '8',
      Name: 'Fidelia Harpin',
      Phone: 1012344569,
      Country: 'New York No. 1 Lake Park',
      Status:'Not Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '9',
      Name: 'Alaina Brim',
      Phone: 1012345687,
      Country: 'New York No. 1 Lake Park',
      Status:'Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '10',
      Name: 'Torie Showman',
      Phone: 10126756789,
      Country: 'New York No. 1 Lake Park',
      Status:'Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '11',
      Name: 'Rayna Suazo',
      Phone: 10134556789,
      Country: 'London No. 1 Lake Park',
      Status:'Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '12',
      Name: 'Evangeline Murrin',
      Phone: 10123656789,
      Country: 'Sidney No. 1 Lake Park',
      Status:'Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
    {
      Code: '13',
      Name: 'Hyacinth Hanson',
      Phone: 10123236789,
      Country: 'London No. 2 Lake Park',
      Status:'Not Active',
      Image:'/avatar/003.jpg',
      Edit:'1',
      Del:'2',
      Car:'3',
    },
  ];
  export default data